import Head from "next/head";
import { useState } from "react";
import HeaderOtherPages from "../components/HeaderOtherPages";
import HeadImage from "../public/resources/mainBanner.jpg";
import styles from "../styles/AssignmentQuery.module.css";
import homestyles from "../styles/Home.module.css";
export default function AssignmentQuery() {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [subject, setSubject] = useState("");
  const [contact, setContact] = useState("");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [words, setWords] = useState("");
  const [deadline, setDeadline] = useState("");
  return (
    <>
      <Head>
        <title>Assignment Query | SUA-Australia</title>
        <meta name="Assignment Query" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderOtherPages headerImage={HeadImage} />
      <main className={homestyles.mainContainer}>
        <div className={styles.Upload}>
          <form action="" method="post">
            <div className={styles.splitFields}>
              {" "}
              <div>
                <label htmlFor="fistname">Firstname</label> <br />
                <input
                  type="text"
                  name="firstname"
                  value={firstName}
                  placeholder="Your Firstname"
                  onChange={(e) => setFirstName(e.target.value)}
                />{" "}
                <br />
              </div>
              <div>
                <label htmlFor="lastname">Lastname</label> <br />
                <input
                  type="text"
                  name="lastname"
                  value={lastName}
                  placeholder="Your Lastname"
                  onChange={(e) => setLastName(e.target.value)}
                />{" "}
                <br />
              </div>
              <div>
                <label htmlFor="email">Email address</label> <br />
                <input
                  type="text"
                  name="email"
                  value={email}
                  placeholder="Your Email"
                  onChange={(e) => setEmail(e.target.value)}
                />{" "}
                <br />
              </div>
              <div>
                <label htmlFor="contact">Contact</label> <br />
                <input
                  type="tel"
                  name="contact"
                  value={contact}
                  placeholder="Your Contact Number"
                  onChange={(e) => setContact(e.target.value)}
                />{" "}
                <br />
              </div>
            </div>

            <div className={styles.splitFields}>
              <div>
                <label htmlFor="subject">Subject</label> <br />
                <input
                  type="text"
                  name="subject"
                  value={subject}
                  placeholder="Query Subject"
                  onChange={(e) => setSubject(e.target.value)}
                />{" "}
                <br />
              </div>
              <div>
                <label htmlFor="title">Title</label> <br />
                <input
                  type="text"
                  name="title"
                  value={title}
                  placeholder="Title"
                  onChange={(e) => setTitle(e.target.value)}
                />{" "}
                <br />
              </div>
              <div>
                <label htmlFor="description">Description</label> <br />
                <input
                  type="text"
                  name="description"
                  value={description}
                  placeholder="Description"
                  onChange={(e) => setDescription(e.target.value)}
                />{" "}
                <br />
              </div>{" "}
              <div>
                <label htmlFor="words">Words</label> <br />
                <input
                  type="number"
                  name="words"
                  value={words}
                  placeholder="Words"
                  onChange={(e) => setWords(e.target.value)}
                />{" "}
                <br />
              </div>
              <div>
                <label htmlFor="deadline">Deadline</label> <br />
                <input
                  type="date"
                  name="deadline"
                  value={deadline}
                  placeholder="Deadline"
                  onChange={(e) => setDeadline(e.target.value)}
                />{" "}
                <br />
              </div>
            </div>
            <button>Get Help</button>
          </form>
        </div>
      </main>
    </>
  );
}
