import Head from "next/head";
import HeaderOtherPages from "../components/HeaderOtherPages";
import HeadImage from "../public/resources/privacypolicy.jpg";
import homestyles from "../styles/Home.module.css";
import uploadstyles from "../styles/AssignmentQuery.module.css";
import styles from "../styles/Contact.module.css";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Privacy Policies | EasyLekh</title>
        <meta name="Privacy Policy" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderOtherPages headerImage={HeadImage} title="Privacy Policy" />
      <main className={homestyles.mainContainer}>
        <div className="col-lg-8 ftco-animate py-md-5 mt-md-5 text-justify">
              <h1>EasyLekh&apos;s Privacy Policy</h1>
              <p>
                We are aware of your concerns regarding the privacy and security
                of personal information. It is our moral responsibility to
                inform you of our privacy policies. What we accomplish with your
                private details is as follows:
              </p>
              <li>
                All student data is exclusively retained inside the business.
              </li>
              <li>
                The organization strictly encrypts all data pertaining to
                pupils.
              </li>
              <li>
                We do not divulge any customer or tutor data to outside parties.
              </li>
              <li>
                Variety of payment gateways manage payments to instantly
                guarantee your secure transaction using debit cards, credit
                cards, and bank transfers. With numerous alternatives including
                Visa, Google Pay, Apple Pay, Razorpay, Discover, and Mastercard,
                payments are quick, simple, and secure.
              </li>
              <li>
                We retain the right to divulge your individually identifiable
                data as required by law but when we assume that disclaimer is
                essential to safeguard our privileges and/or to comply with a
                judicial proceeding, court order, or legal process served on our
                Website. We have worked together so that only they can (and not
                our corporation) can handle a student&apos;s credit card
                information.
              </li>
              <li>
                Easylekh.com has the right to change this privacy
                policy at any moment, so please check back often. Any
                modifications to the aforementioned policy would be published
                here, and your continuing use of the website, its services,
                and/or its software will signify your acceptance of the modified
                terms.
              </li>
              <li>
                Since we respect your privacy, we wish to let you know that you
                will start receiving our emails once you sign up to use our
                service. Your email addresses are treated with the highest care
                and are never shared with anybody. So you can relax knowing that
                every email we send is just for your advantage.
              </li>
            </div>
      </main>
    </>
  );
}
