import Head from "next/head";
import HeaderOtherPages from "../components/HeaderOtherPages";
import HeadImage from "../public/resources/refundPolicyBanner.jpg";
import homestyles from "../styles/Home.module.css";
import uploadstyles from "../styles/AssignmentQuery.module.css";
import styles from "../styles/Contact.module.css";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Refund Policies | EasyLekh</title>
        <meta name="Refund Policies" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderOtherPages headerImage={HeadImage} title="Refund Policies" />
      <main className={homestyles.mainContainer}>
        <div className="col-lg-8 ftco-animate py-md-5 mt-md-5 text-justify">
              <h2 className="text-left">
                EasyLekh Policies regarding Money-back Guarantee/Refund
              </h2>
              <p>
                The supplier shall deliver the product on a regular basis and in
                accordance with the specifications specified by the customer
                with in order. The consumer is entitled to a partial or full
                refund in accordance with our policy should the company fail to
                uphold any of its obligations.
              </p>
              <p>
                The supplier shall deliver the product on a regular basis and in
                accordance with the specifications specified by the customer
                with in order. The consumer is entitled to a partial or full
                refund in accordance with our policy should the company fail to
                uphold any of its obligations.
              </p>
              <h3 className="text-left">
                Case of Cancellation by Customer/ Partial Delivery / No Delivery
              </h3>
              <ul>
                <li>
                  No Expert Assigned: Although it&apos;s uncommon, this
                  situation does occasionally arise. The refund is always 100%
                  of the purchase price. The consumer need not be concerned if
                  such an event does take place because they will be informed as
                  promptly as possible.
                </li>
                <li>
                  You made the decision to cancel the purchase even though the
                  teacher had been confirmed and less thany half the deadline
                  had passed. In this instance, the return amount ranges from
                  100% to 75% to account for the corporate and tutor&apos;s
                  efforts to give you with both the purchased goods and
                  services.
                </li>
                <li>
                  Even though the instructor was booked and more than half of
                  the timeline remained, the customer nevertheless chose to
                  cancel the transaction. The amount of such refund may range
                  from 50% to 0% to reflect the tutor&apos;s and business&apos;s
                  efforts to fulfil your order request.
                </li>
                <li>
                  Late Delivery: This only occurs in the event of the tutor
                  becoming ill or other exigencies. If there are delays, the
                  customer has the option to ask for a refund—BUT Unless the
                  CUSTOMER Has Still not DOWNLOADED THE TUTOR&apos;S SUBMITTED
                  WORK. If the student downloads the tutor&apos;s work, they
                  forfeit their right to a refund and are assumed to have
                  utilised it.
                </li>
                <li>
                  All orders will be delivered on time, it is assured. The
                  customer&apos;s uploading of necessary materials too late
                  might occasionally cause delays. There can be no reimbursement
                  in this case. Because of this, it is always best to give all
                  relevant information about the assignment at once, along with
                  any supplementary sources that will be needed.
                </li>
              </ul>
              <h3 className="text-left">Transaction/Duplicate Order</h3>
              <ul>
                <li>
                  Duplicate Order Accidently: In order to cancel an order placed
                  by mistake in duplicate, you need to contact the company
                  within 24 hours for the duplicate order and request for a
                  refund. If the order is found to be duplicate and was ordered
                  unintentionally, 100% refund will be issued
                </li>
                <li>
                  Duplicate Transaction Accidently: In case extra/duplicate
                  payment is processed against the same order for which payment
                  has already been done earlier, the same will be 100% refunded
                  on filing a request
                </li>
              </ul>
              <h3 className="text-left">
                You are not Eligible for Refund in case:{' '}
              </h3>
              <ul>
                <li>
                  Getting lower grades: Please remember that grades are NOT
                  guaranteed. The articles that we offer are intended simply as
                  rough draught examples or as a point of reference; they are
                  not complete and should not be presented as one&apos;s own
                  work.
                </li>
                <li>
                  Changes in deadline: Because the end deadlines are distinct,
                  the refunds for delays described above and the recompilation
                  of the cost do not apply in situations where the deadline has
                  changed.
                </li>
                <li>
                  Orders including editing, proofreading, and formatting: Please
                  be aware that the data in your order for the aforementioned
                  services was originally produced by you and might contain
                  context errors. Editing and formatting are solely used for
                  more detailed changes and feedback pertaining to spelling,
                  formatting, content knowledge, flow, grammar, and/or other
                  comparable elements. They do not result in a major
                  modification to the actual document.
                </li>
                <li>
                  Documentation procedure and proof: In the event that the
                  Customer fails to comply with the procedures and deadlines set
                  forth in Section 5 for legal complaints, refund requests, and
                  complaints
                </li>
              </ul>
              <h3 className="text-left">
                Refund and Response Processing Timelines And Process
              </h3>
              <p>
                Due to the subjective nature of the task, a customer&apos;s
                assessment of the quality of the task and delivery can differ
                first from tutor&apos;s. To be entitled for a refund in these
                circumstances, the client must submit each and every claims,
                grievances, or refund requests in accordance with the
                prescriptions below:
              </p>
              <ul>
                <li>
                  Give the request&apos;s evaluation and decision-making a
                  minimum of 7 days of work.
                </li>
                <li>
                  All claims, complaints, and refund requests must be made using
                  the customer&apos;s online account and supported by the
                  necessary documentation, in accordance with this policy&apos;s
                  and also the terms of service.
                </li>
                <li>
                  Give customers a minimum of 7 days of work to receive refunds
                  after the organization has informed them of the decision.
                </li>
              </ul>
              <h3>Work is Not Relative</h3>
              <ul>
                <li>
                  The business offers specialized work that is created to meet
                  the needs of the client. The customer is given a draught of
                  the initial work, which will be developed further based on
                  their comments.
                </li>
                <li>
                  Disputed claims: If a client requests a refund but is
                  dissatisfied with the work&apos;s quality and requirements,
                  the business is required to address the client&apos;s
                  complaints and make the necessary corrections. The customer
                  may seek a correction up to 30/45/60 days after the initial
                  submission date, depending on the plan they choose. Within
                  seven days after receiving the service, the client has the
                  option to demand a refund by presenting pertinent
                  documentation if they are still unsatisfied. The
                  investigation&apos;s findings, which heavily rely on the
                  case&apos;s circumstances and the customer&apos;s supporting
                  documentation, will determine whether the refund request is
                  accepted or rejected.
                </li>
                <li>
                  Plagiarized content: When there is a complaint that the
                  instructor&apos;s work is plagiarised, the customer must give
                  a third-party verified report within 72 hours of obtaining the
                  allegedly plagiarised work. If the claim is verified, the
                  consumer will receive a complete refund.
                </li>
              </ul>
            </div>
      </main>
    </>
  );
}
