import Head from "next/head";
import HeaderOtherPages from "../components/HeaderOtherPages";
import HeadImage from "../public/resources/t&cBanner.jpg";
import homestyles from "../styles/Home.module.css";
import uploadstyles from "../styles/AssignmentQuery.module.css";
import styles from "../styles/Contact.module.css";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Terms & Conditions | EasyLekh</title>
        <meta name="Terms & Conditions" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderOtherPages headerImage={HeadImage} title="Terms & Conditions" />
      <main className={homestyles.mainContainer}>
        <div className="col-lg-8 ftco-animate py-md-5 mt-md-5 text-justify">
              <h3>Terms of Use</h3>
              <p className="text-justify">
                Please Read These Terms Carefully Before Using our Service. The
                use of easylekh.com is only to be undertaken by those
                of legal age. Any improper usage is strictly prohibited. Once
                you have placed an order on this website, you have confirmed
                that you have read, understood, and agreed with all our Terms
                and Conditions. Submitting a request and/or payment implies that
                you are legally obligated to abide by these Terms and
                Conditions.
              </p>
              <h4>Interpretation Of Our Terms:</h4>
              <ul>
                <li>
                  <strong>&quot;Website&quot; </strong>means
                  easylekh.com
                </li>
                <li>
                  <strong>&quot;Consumer/Customer&quot; </strong>,{' '}
                  <strong>&quot;You&quot; or &quot;Yours&quot; </strong>
                  refers to anyone submitting, bidding, executing an order,
                  uploading any information, and transferring payments on this
                  website.
                </li>
                <li>
                  <strong> Chat System </strong>is the software that ensures
                  uninterrupted communication between the Customer and the Team,
                  or with a Support Team Representative.
                </li>
                <li>
                  <strong> Order </strong>refers to the actual request for a
                  Service sent to our Company by the Customer. It includes
                  particular requirements and a specification of sources to be
                  used in writing. <br /> or <br />{' '}
                  <strong> An &apos;Order&apos; </strong> is an electronic
                  request for a paid service from the Customer for a particular
                  writing service. An order specifies the scope of work and
                  other requirements of the Customer regarding the service. or
                  &quot;Order&quot; refers to the written order that was
                  submitted in electronic form online on our website by the
                  consumer. An order includes the work in its entirety, along
                  with its consumer requirements.
                </li>
                <li>
                  <strong> Status </strong>shows the progress of the Order and
                  current position towards completion.
                </li>
                <li>
                  <strong> Quality Assurance Department </strong> refers to the
                  Company&apos;s structural unit responsible for evaluating and
                  protecting the quality of our Products and Services. <br /> or{' '}
                  <br />{' '}
                  <strong>
                    {' '}
                    The &apos;Quality Assurance Department&apos;{' '}
                  </strong>{' '}
                  is the entity in easylekh.com infrastructure, whose
                  mission is to guard and evaluate the quality of the products
                  and services provided.
                </li>
                <li>
                  <strong> Support Team or Support </strong> refers to the
                  Company&apos;s structural unit responsible for coordinating
                  and assisting the Order process.
                </li>
                <li>
                  <strong> The Writer </strong> is a person employed by the
                  Company who provides research and writing services to the
                  Customer, according to the Company Agreement.
                </li>
              </ul>
              <h4>Order Placing and Registration</h4>
              <ul>
                <li>
                  The order is placed by completing the Order form provided in
                  the Application. No Service is provided by other means than by
                  request.
                </li>
                <li>
                  The Order form will specify the scope of the work, Order
                  parameters, and delivery terms. It is Your personal
                  responsibility to provide exact, full, and final information
                  to each standard Order form section when filling in Our Order
                  form.
                </li>
                <li>
                  You will be requested to register by providing Your contact
                  information such as name, email address, country of residence,
                  and telephone number. Should any difficulties arise during the
                  process of account creation, please contact our Support. In
                  addition, should any of your contact details change over time,
                  it is your sole responsibility to update your profile
                  accordingly or inform Support of such changes.
                </li>
                <li>
                  Should multiple accounts be discovered, they will be merged
                  with your initial account created during Your first purchase.
                </li>
              </ul>
              <h3>Company&apos;s Responsibility</h3>
              <ul>
                <li>
                  The Company has a zero-tolerance policy regarding plagiarism,
                  academic dishonesty, and fraud. We will not be held
                  accountable if such unethical and illegal use of our products
                  and Website content occurs.
                </li>
                <li>
                  We strictly abide by all Copyright laws. Any opposing activity
                  is solely the responsibility of the Customer if they break our
                  Terms and Conditions.
                </li>
                <li>
                  Disclaimer for Links Used on easylekh.com: While
                  this website may include links to other websites, we do not
                  condone, approve, or guarantee that the content of these links
                  complies with the Terms and Conditions of
                  easylekh.com. As such, our Company does not own, is
                  not responsible for, and does not contribute or control any of
                  the content stemming from the posted links on our website.
                  Visiting these links is agreed upon as your own risk based
                  upon the user agreement form that is submitted with your order
                  form.
                </li>
                <li>
                  <strong> Security and Privacy: </strong>Our Privacy Statement
                  posted on this website may be referred to for more detailed
                  information regarding our Company&apos;s practices and
                  policies concerning the collection, storage, and use of Client
                  and online guests&apos; information. To learn more about your
                  personal informations security while using this website,
                  please visit the Privacy Policy webpage. The Company reserves
                  the right to contact the customers by email regarding new
                  services, discounts, special offers, and any other information
                  that the Company may deem useful for the customers. However,
                  with that in mind it is important to note that we highly value
                  the privacy of our customers and will not disclose their
                  personal and billing information to any third parties. To
                  ensure their data remains protected, the Company processes all
                  transactions through a secure online payment system. Note: It
                  is important to note that the Company cannot be held
                  responsible if credit information gets disclosed without our
                  Company&apos;s consent or beyond its control. Should any
                  privacy or security questions arise, the Customer is welcomed
                  to refer to our Privacy Policy.
                </li>
              </ul>
              <h3>Warranties</h3>
              <p>
                Once you have submitted your order or payment, you agree and
                acknowledge all of the following points and statements: All our
                written products for or by Consumers are solely intended to be
                used for research, reference, or learning purposes on how to
                properly write an academic paper within a certain citation style
                (i.e. APA, MLA, Chicago, Harvard, etc.). All and any information
                as well as ideas that are used from the provided written works
                must be properly cited if they are referenced at a later date.
                All consumers agree that all services rendered on this website
                require payment for the time and effort that are used to gather,
                organise, correct, edit, and deliver the service to the consumer
                after completion. Additionally, payment is used to maintain the
                website for further educational use by our Consumers. Other than
                a conservative number of printed copies for personal and
                educational use, the distribution, publication, transmission,
                modification, display, or derivative works may not be created
                from the final delivered service by the Company without prior
                written consent from the Company.All written products from our
                freelance consumers automatically transfer all authorship rights
                and ownership to the Company and/or its partners. You, the
                consumer, agree to destroy any and all delivered products from
                the Company after your research/reference purposes for the paper
                have been completed. No copies for redistributive purposes are
                allowed nor are our works to be used elsewhere without proper
                consent or citation. By using our services, you the consumer
                agree to receive promotional information such as specials,
                contests, and discounts from the Company. You may unsubscribe
                from or subscribe to receiving such information in your profile
                directly. Our Company makes no warranties or representations of
                warranties in regard to our website or its materials, stated or
                implied, that arise by law or otherwise. This includes, without
                any limitation, a warranty of merchantability or suitability for
                a non-infringement, particular purpose, or any other implied
                guarantee or warranty that arises from the performance or deal
                with usage of trade. Additionally, the Company does not
                guarantee that our operation will run error-free, and we are not
                responsible for any repercussions from any errors that arise on
                our website. It is up to the consumer to ensure the accuracy,
                usefulness, or completeness with any opinion, information,
                advice, or other content that is related to this service or
                available on this website. Please seek professional opinions
                before using any available services on our website.
              </p>
              <h3>Limitation Of Liability</h3>
              <p>
                Agreeing to all the above Terms and Conditions, you acknowledge
                that you agree not to hold other Consumers, the Company, its
                employees, shareholders, agents, officers, directors,
                representatives, promotion, affiliates, subsidiaries,
                advertising, fulfillment agencies, or any other third-party
                providers or information/data sources and legal advisors
                responsible for any and all losses, damages, rights, actions,
                and claims of any nature that come from or are related to our
                Company. These products include but are not limited to
              </p>
              <ul>
                <li>
                  telephone, hardware or software, electronic, Internet, email,
                  network, computer malfunctions, difficulties or failures of
                  any kind.
                </li>
                <li>
                  unclear, failed, delayed, or incomplete computer
                  communications and transmissions;
                </li>
                <li>
                  any condition that arises due to the events that lie beyond
                  the Company&apos;s control that cause the service to be
                  delayed, disrupted, or corrupted.
                </li>
                <li>
                  any injuries, losses, or damages of any kind that arise with
                  connection to or as a result of using our services
                </li>
                <li>
                  any typographical errors or printing mistakes in any of our
                  materials associated with our services.
                </li>
              </ul>
              <p>
                Additionally, you agree to not hold our Company and its
                affiliates responsible or reprehensible for any claim, demand,
                suit, including attorney&apos;s fees, made by another third
                party in relation to or arising from the use of our service,
                your breach or violation of these Terms and Conditions, the
                violation by you of the rights of any third party, or any other
                personal act of omission committed by you. Under no circumstance
                will the Company be made responsible or liable for any direct,
                indirect, punitive, incidental, consequential, or special
                damages that arise from or are in any way related to the use of
                this website and any of its provided information. Some states
                and jurisdictions do not allow the limitation or exclusion of
                liability for incidental or consequential damages. As such, the
                above-listed limitation may not be applicable to you.
              </p>
              <p>
                <strong> Termination: </strong> We reserve the right to
                terminate your right to use our Services even when you have paid
                the full amount if the information initially provided for
                registration on our Services or that is later subsequently
                modified, contains false or misleading information, or conceals
                or omits any information we consider as being relevant; if you
                do not cooperate throughout the ordering process; if we suspect
                that you are involved in any fraudulent transactions. Any
                attempt to undermine or cause harm to
                easylekh.com&apos;s server or its customers is
                strictly prohibited and will be subject to automatic account
                termination. This includes spamming, transmission of - malware,
                viruses, trojan horses; or by linking to sites and files that
                contain or distribute them. easylekh.com may terminate
                your account and forfeit any fee to be paid at any time without
                prior notice, if you are in breach of the terms of this
                Agreement. The Company will be the sole arbiter as to what
                constitutes a violation of the Agreement.
              </p>
              <p>
                <strong> Amendments:</strong> You, the consumer, acknowledge and
                agree that these Terms and Conditions may be completely or
                unilaterally changed by the Company without prior warning. It
                is, therefore, highly recommended that all Consumers on our
                website read these Terms and Conditions from time-to-time to see
                if any changes have been made.
              </p>
              <p>
                <strong> Governing Law:</strong> These Terms of Use and any
                non-contractual obligations arising out of or in connection with
                them shall be governed by, and construed in accordance with the
                laws of the Republic of Cyprus. Any dispute, controversy or
                claim arising out of or in connection with these Terms of Use,
                or the breach, termination or invalidity thereof, shall be
                finally settled by courts of the Republic of Cyprus.
              </p>
            </div>
      </main>
    </>
  );
}
