import Head from "next/head";
import homestyles from "../../styles/Home.module.css";
import styles from "../../styles/BlogId.module.css";
import Navbar from "../../components/layout/Navbar";
import Link from "next/link";
import UploadForm from "../../components/UploadForm";
import SidebarList from "../../components/SidebarList";
import { useRouter } from "next/router";

export const getStaticPaths = async () => {
  const res = await fetch("https://api.swipeupassignments.com/blogs");
  const data = await res.json();
  // console.log(data.data);
  const paths = data.data.map((blog) => {
    return {
      params: { id: blog.id.toString() },
    };
  });
  // console.log(paths);
  return {
    paths,
    fallback: false,
  };
};
export const getStaticProps = async (context) => {
  const id = context.params.id;
  const res = await fetch("https://api.swipeupassignments.com/blogs/" + id);
  const data = await res.json();
  return {
    props: { blog: data },
  };
};
export default function IndividualBlog({ blog }) {
  const currentRoute = useRouter().pathname;
  return (
    <>
      <Head>
        <title>{blog.title} | SUA-Australia</title>
        <meta name="Assignment Query" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <GoogleAnalytics /> */}
      </Head>
      <div className={styles.HeaderOtherPages}>
        <div
          style={{
            backgroundImage: `url(${blog.thumbnail})`,
          }}
          className={styles.headerotherOverlay}
        ></div>
        {/* <LogoSection /> */}
        <Navbar />
        <div className={styles.pageIndicator}>
          <h3>
            <Link href="/">Home/ </Link>
            <span>blog</span>
          </h3>
          <h1>{blog.title}</h1>
        </div>
      </div>
      <main className={homestyles.mainContainer}>
        <section className={styles.blogFlexbox}>
          <article className={styles.blogDataContainer}>
            {" "}
            <p>{new Date(blog.createdAt).toDateString()}</p>{" "}
            {/* {console.log(blog.thumbnail)} */}
            <div dangerouslySetInnerHTML={{ __html: blog.description }}></div>
          </article>
          <article className={styles.sideBar}>
            <UploadForm />
            <SidebarList />
          </article>
        </section>
      </main>
    </>
  );
}
