import Head from "next/head";
import Blogs from "../../components/Blogs";
import HeaderOtherPages from "../../components/HeaderOtherPages";
import HeadImage from "../../public/resources/mainBanner.jpg";
export default function AllBlogs() {
  return (
    <div>
      <Head>
        <title>Upload | SUA-Australia</title>
        <meta name="upload" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderOtherPages headerImage={HeadImage} />
      <div>
        <Blogs />
      </div>
    </div>
  );
}
