import Head from "next/head";
import Blogs from "../../components/Blogs";
import HeaderOtherPages from "../../components/HeaderOtherPages";
import HeadImage from "../../public/resources/blogsBanner.jpg";
import styles from "../../styles/Home.module.css";
export default function AllBlogs() {
  return (
    <>
      <Head>
        <title>Blogs | SUA-Australia</title>
        <meta name="upload" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderOtherPages headerImage={HeadImage} title="Blogs" />
      <main className={styles.mainContainer}>
        <Blogs />
      </main>
    </>
  );
}
